version: "3.9"
services:
  nginx-ingress:
    build: ./nginx-ingress
    image: "nginx-ingress"
    logging:
      driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  ssh-gw:
    build: ./ssh-gw
    image: "ssh-gw"
    logging:
      driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  debian-pc:
    build: ./debian-pc
    image: "debian-pc"
    init:  true
    environment:
      - HOSTNAME=debian-pc
      - RC_LOCAL_SCRIPT_URL=https://raw.githubusercontent.com/sysbuild-training/hands-on-plugins/main/lpic-2024q2/rc.local
    volumes:
      - /var/tmp/shared:/tmp/.shared
    logging:
      driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
