version: "3.9"
services:
  nginx-ingress:
    ports:
      - "80:80"
    volumes:
      - ./work/etc/nginx/conf.d/:/etc/nginx/conf.d
  ssh-gw:
    ports:
      - "22:22"
    volumes:
      - ./work/etc/ssh:/etc/ssh
  testweb:
    build: ./testweb
    image: "testweb"
